### ISSUE TITLE
Rework Ages to make more sense on Mars

### ISSUE THREAD

**Issue by SevyRide** [Firesoul7/Mars_Universalis#17]
I'm thinking something like:
1: Age of Planetfall  (focus young colonies/new arrivals)
2: Age of Reforms  (focus atlanteans/remnants)
3: Age of Expansion  (focus on expansion, as in getting most of the landmass belonging to a nation)
4: Age of Inovation  (focus on rennesaince/enlightenment movements, so tech and cultural advancement)

After this, I'm not sure, but depending on how long the timeline is supposed to go, eventually something like: ( industrialization/urbanization -> chemical revolution -> automation -> Information revolution ) or something?

**Comment by Firesoul7** [comment]
Notes: I was looking for the original planned names for this, but I can't find them. I remember that there was a plan in place but not what that plan was

**Comment by Firesoul7** [comment]
![ages](https://user-images.githubusercontent.com/13421958/46697921-b0580600-cc0d-11e8-8b23-27c1dd8c3252.jpeg)
I found the information

**Comment by Firesoul7** [comment]
Effectively the ideas are the same, but the names are a little different in the original plan

**Comment by Firesoul7** [comment]
We all agreed that this needs doing before we go public with the next version

**Comment by Firesoul7** [comment]
This is finally finished.
