### ISSUE TITLE
Egypt Remnant

### ISSUE THREAD

**Issue by Firesoul7** [Firesoul7/Mars_Universalis#24]
https://imgur.com/35dU2oL

**Comment by sethbrisby** [comment]
I'd like to take over this task, if its alright with you

**Comment by Firesoul7** [comment]
Ok, but there are certain requirements:

The two main nations must be Upper and Lower Egypt, and both must be Sunni. Whether the rest are Sunni or Ancient Egyptian is up to you. 

An Egyptian OPM is planned for the empty island east of the remnant. Can be Sunni or Egyptian.

The borders of the remnant must be strictly respected

**Comment by sethbrisby** [comment]
Okay, I can do that. I was thinking about a Nile style river down the canyon, flowing east.

**Comment by Firesoul7** [comment]
Yes, having a Nile type river would be very good and make it closer to the lore, thanks.

Yes, that island, and both provinces. I thought it was just one province, but you're right, it's two. My idea for it was to have a sort of Lighthouse of Alexandria there (in the lore at least) though mainly it just has to be occupied. The little island east of it (Chenel) could also be given to the Egyptians if you want

**Comment by Firesoul7** [comment]
This is finally finished. I'm not sure if there's anything further that needs saying about the matter. Idea sets are still required for most of them.
