### ISSUE TITLE
Scandinavian Remnant

### ISSUE THREAD

**Issue by Firesoul7** [Firesoul7/Mars_Universalis#30]
https://cdn.discordapp.com/attachments/460549990272466963/558404553528049684/unknown.png

**Comment by EmperorPenguin117** [comment]
![image](https://user-images.githubusercontent.com/40343171/54788338-4a2bd200-4bf4-11e9-9a77-93e1654fcc0e.png)

**Comment by Firesoul7** [comment]
My ideas here:

Every province in the remnant will be its own tag, with a CK2-esque system above them whereby the whole thing is split into a number of duchies, with any of the counties assigned to the duchy able to form it, then above each duchy three kingdoms of Denmark (the big island), Norway (southern half of the mainland, slightly smaller than Sweden), and Sweden (northern half of the mainland). The two small islands will belong to the honorary kingdom of Gotland (bigger of the small of Gotland, smaller of the small is Bornholm, which as a county would be able to form Gotland if it conquered the other small island), with its own culture etc. Above all the kingdoms will be the empire of Scandinavia, requiring control of the whole remnant.

Counties will take their names from Scandinavian cities, duchies from Scandinavian regions. Group sets will be created for the Danes, Swedes, Norwegians, and Gotlanders.

**Comment by Firesoul7** [comment]
Finished
